title: Ganesh Balaji
description: Computational engineering undergrad at IIT Madras.
about: Computational engineering undergrad at IIT Madras.
github: https://github.com/gnshb
x: "#"
linkedin: "#"
math_stackexchange_url: https://math.stackexchange.com/users/734160/datboi
math_stackexchange_flair: https://math.stackexchange.com/users/flair/734160.png?
